### ISSUE TITLE
Angular Server Side Rendering

### ISSUE THREAD

**Issue by alexandreszczepaniak** [fingerprintjs/fingerprintjs-angular-example#1]
Any chance to support Server side rendering in the future ?

**Comment by makma** [comment]
Hi @alexandreszczepaniak, I'm sorry we missed this issue.

Yes, angular SSR is on our radar and we want to address this at some point. Can you please describe your use case? How would you like to use the API? Any additional context and resources are more than welcomed and will help us prioritise this.

**Comment by alexandreszczepaniak** [comment]
Hi @makma thanks for your response.
I'm using the pro-package & getting the visitor ID with the exemple you gave in the README in SSR.
The current error is: "ReferenceError: location is not defined".
I somehow made it work on another app by coincidence it seems, maybe because of a polyfills.
Since you asked, is there any plan to implement tree-shaking to the package ?

**Comment by makma** [comment]
Hi @alexandreszczepaniak!
**Re document location:** I'll check it tomorrow. Also, I'll discuss it with our tech folks internally.
**Re tree-shaking:** What version of the pro agent do you use? We've improved [tree-shaking capabilities in the v3.5.3](https://dev.fingerprintjs.com/changelog/3-5-3).

**Comment by makma** [comment]
Hey @alexandreszczepaniak!
Probably the best practice for the server-side rendering use-case is getting the `visitorId` after a platform check. For Angular, I used `isPlatformBrowser` function inside my SSR project and everything worked smoothly. 

```ts
import { Component } from '@angular/core';
import FingerprintJS from '@fingerprintjs/fingerprintjs-pro';
import { isPlatformBrowser } from '@angular/common';
import { Inject }  from '@angular/core';
import { PLATFORM_ID } from '@angular/core';

const BROWSERAPIKEY = '***';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css'],
})
export class AppComponent {
  title: string = 'fpjs-angular';
  visitorId: string = 'Waiting...';

  constructor( @Inject(PLATFORM_ID) platformId: Object) {
    if (isPlatformBrowser(platformId)) {
      this.getVisitorID();
    }
  }

  public getVisitorID(): void {
    FingerprintJS.load({
      token: BROWSERAPIKEY,
    })
      .then((fp) => fp.get())
      .then((result) => {
        this.visitorId = result.visitorId;
        console.log(result);
      });
  }
}
```

What do you think?

**Comment by alexandreszczepaniak** [comment]
Indeed, it's working perfectly. I did not know isPlatformBrowser worked like that thanks.

**Comment by makma** [comment]
Glad to hear that @alexandreszczepaniak! 

From my understanding of the server-side rendering, it doesn't make sense to execute fingerprinting-related code on the server-side. Therefore, it doesn't make sense to make the FingerprintJS Pro agent platform-agnostic (without browser APIs, e.g. `document.location`).

> I somehow made it work on another app by coincidence it seems, maybe because of a polyfills.

Can you tell me more about how you solved it at first?

**Comment by alexandreszczepaniak** [comment]
I can't tell you, unfortunately. I lost the project and can't reproduce it.

**Comment by makma** [comment]
Ok, thank you anyways :)
